# Generated by Django 3.2.8 on 2021-10-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosisApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='age',
            field=models.IntegerField(),
        ),
    ]
