# Generated by Django 3.2.8 on 2021-10-09 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nosisApp', '0002_alter_user_data_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_data',
            name='symptoms',
            field=models.TextField(default='None'),
        ),
    ]
